AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Website

Parameters:
  ACMArn:
    Type: String
    Description: ARN for a certificate in us-east-1 for CloudFront Distribution
  WebACLId:
    Type: String
    Description: ID for web ACL to protect CloudFront Distribution
    Default: ""
  CNAMEs:
    Type: CommaDelimitedList
    Description: CSV of CNAMES for the CloudFront Distribution
  HostedZoneName:
    Type: String
    Description: Name of Route53 zone

Conditions:
  HasWebACL:
    Fn::Not:
      - !Equals
        - Ref: WebACLId
        - ""
Resources:
  WebBucket:
    Type: AWS::S3::Bucket

  CloudFrontIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "Access identity for web"

  WebBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: WebBucket
    Properties:
      Bucket:
        Ref: WebBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Principal:
              AWS:
                !Join
                  - ' '
                  - - arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity
                    - Ref: CloudFrontIdentity
            Resource:
              - !GetAtt
                - WebBucket
                - Arn
              - !Join
                - /
                - - !GetAtt
                      - WebBucket
                      - Arn
                  - '*'

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn: WebBucket
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        ViewerCertificate:
          SslSupportMethod: sni-only
          AcmCertificateArn:
            Ref: ACMArn
        WebACLId:
          !If
            - HasWebACL
            - Ref: WebACLId
            - Ref: AWS::NoValue
        Aliases:
          Ref: CNAMEs
        DefaultCacheBehavior:
          TargetOriginId: S3-Primary
          ForwardedValues:
            QueryString: false
          Compress: true
          ViewerProtocolPolicy: redirect-to-https
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        Origins:
          - Id: S3-Primary
            DomainName:
              !GetAtt
                - WebBucket
                - DomainName
            S3OriginConfig:
              OriginAccessIdentity:
                !Join
                  - /
                  - - origin-access-identity/cloudfront
                    - Ref: CloudFrontIdentity

  WwwDnsRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName:
        Ref: HostedZoneName
      RecordSets:
        - Name:
            !Select
              - 0
              - Ref: CNAMEs
          Type: A
          AliasTarget:
            # HostedZone for cloudfront is always this value https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName:
              !GetAtt:
                - CloudfrontDistribution
                - DomainName

Outputs:
  WebBucket:
    Description: Web Hosting Bucket
    Value:
      Ref: WebBucket
  CloudfrontDistribution:
    Description: Web Distribution ID
    Value:
      Ref: CloudfrontDistribution