name: deploy to s3

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    - run: |
        npm ci
        npm run build --if-present
        npm test
        npm run export
    - name: Deploy
      id: blog
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      env:
        CNAMES: 'sajangurung.com'
        HOSTED_ZONE: 'sajangurung.com.'
      with:
        name: blog
        template: template.yaml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: >-
          ACMArn=${{ secrets.ACMARN }},
          CNAMEs=${{ env.CNAMES }},
          HostedZoneName=${{ env.HOSTED_ZONE }}
    - name: Copy files to s3 bucket
      env:
        WEBBUCKET: 'E29NYYDSQNHXX'
        DISTRIBUTION: 'blog-webbucket-1excsx8k0cmn8'
      run: |
        aws s3 sync out/ s3://"${{ env.WEBBUCKET }}" --delete
        aws cloudfront create-invalidation --distribution-id "${{ env.CloudfrontDistribution }}" --paths / /index.html