name: deploy to s3

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test